nodeLinker: node-modules

npmAuditRegistry: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.5.2.cjs

#enableStrictSsl: false
httpProxy: http://127.0.0.1:7890
httpsProxy: http://127.0.0.1:7890
