[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]

[target.x86_64-windows-msvc]
linker = "x86_64-w64-mingw32-gcc"
rustflags = ["-C", "target-feature=-crt-static"]

[build]
target-dir = "target"
